---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dataviz

The goal of dataviz is to supply data and load packages that we use in the BU R training sessions.

## Installation

You can install dataviz from [GitHub](https://github.com/) with:

``` r
install.packages("remotes")
```

``` r
remotes::install_github("teaching-mjg/dataviz")
```

If you're using AppsAnywhere, add 
`lib="C:/ProgramData/R/win-library/4.2"` like this
``` r
install.packages("remotes")
```
``` r 
remotes::install_github("teaching-mjg/dataviz", lib="C:/ProgramData/R/win-library/4.2")
```
## Reference

A website with reference material for the package is at [https://teaching-mjg.github.io/dataviz/](https://teaching-mjg.github.io/dataviz/).

## Example

This is how to start using dataviz:

```{r example}
library(dataviz)
```


